Repository SW-Team2/se-team2-tetris, pull requests merged in 2022-03, with the labels that each got.

#2 feat: 점수 계산 추가, 점수를 화면에 출력(임시)
  src/tetrisgame/GameBoard.java
  src/tetrisgame/TetrisGame.java
  src/tetrisgame/Tetromino.java
Labels: 🌈 feature

#8 fix: 링크된 2개의 버그
  src/tetrisgame/GameBoard.java
  src/tetrisgame/TetrisGame.java
  src/tetrisgame/Tetromino.java
Labels: 😢 bug

#9 feature: 임시 GUI클래스 입니다. 화면 전환이 가능합니다.
  src/graphics/WindowManager.java
  src/graphics/screens/GameScreen.java
  src/graphics/screens/MainMenuScreen.java
  src/graphics/screens/ScoreBoardScreen.java
  src/graphics/screens/SettingMenuScreen.java
Labels: 🌈 feature

#13 feature, refact: data패키지 추가, tetrigame패키지 파일 구조 변경
  src/data/score/ScoreBoardInfo.java
  src/data/score/ScoreInfo.java
  src/data/setting/SettingInfoDesc.java
  src/graphics/WindowManager.java
  src/graphics/screens/GameScreen.java
  src/graphics/screens/SettingMenuScreen.java
  src/tetrisgame/Enums.java
  src/tetrisgame/TetrisGame.java
  src/tetrisgame/enumerations/eCollResult.java
  src/tetrisgame/enumerations/eDirection.java
  src/tetrisgame/enumerations/eGameOver.java
  src/tetrisgame/parts/Block.java
  src/tetrisgame/parts/GameBoard.java
  src/tetrisgame/parts/Position.java
  src/tetrisgame/parts/Tetromino.java
  src/tetrisgame/parts/Timer.java
Labels: 🌈 feature, 🏭 refactor

#26 Feat/issue-24: PR, Issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/new_feature.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📄 documentation
