Repository SW-Team2/se-team2-tetris, pull requests merged in 2022-04, with the labels that each got.

#28 Msg manager
  src/TestMain.java
  src/graphics/WindowManager.java
  src/graphics/eScreenInfo.java
  src/graphics/screens/GameScreen.java
  src/graphics/screens/MainMenuScreen.java
  src/graphics/screens/ScoreBoardScreen.java
  src/graphics/screens/Screen.java
  src/graphics/screens/SettingMenuScreen.java
  src/tetrisgame/TetrisGame.java
Labels: 🌈 feature

#31 Feat/issue 30
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/Calculator.java
  src/test/java/CalculatorTest.java
Labels: 🌈 feature, 💡 test

#36 feature: 2차 req 게임 기능
  src/TestMain.java
  src/gamestarter/GameStarter.java
  src/graphics/WindowManager.java
  src/graphics/screens/GameScreen.java
  src/res/background/background_board.png
  src/res/background/background_nextboard.png
  src/res/background/background_panel.png
  src/res/tile/tile_blue.png
  src/res/tile/tile_frame.png
  src/res/tile/tile_lightgreen.png
  src/res/tile/tile_orange.png
  src/res/tile/tile_purple.png
  src/res/tile/tile_red.png
  src/res/tile/tile_remove1.png
  src/res/tile/tile_remove2.png
  src/res/tile/tile_skyblue.png
  src/res/tile/tile_white.png
  src/res/tile/tile_yellow.png
  src/tetrisgame/TetrisGame.java
  src/tetrisgame/enumerations/eDifficulty.java
  src/tetrisgame/parts/Block.java
  src/tetrisgame/parts/GameBoard.java
  src/tetrisgame/parts/ImageLoader.java
  src/tetrisgame/parts/Tetromino.java
  src/tetrisgame/parts/Tile.java
  src/tetrisgame/parts/Timer.java
Labels: 🌈 feature

#46 Game component base
  .gitignore
  .vscode/launch.json
  src/TestMain.java
  src/graphics/WindowManager.java
  src/graphics/eScreenInfo.java
  src/graphics/screens/GameScreen.java
  src/graphics/screens/ItemModeGameScreen.java
  src/graphics/screens/MainMenuScreen.java
  src/res/tile/item_tile_lineeraser.png
  src/res/tile/item_tile_removingall.png
  src/res/tile/item_tile_slowing.png
  src/res/tile/item_tile_weight.png
  src/res/tile/tile_item_bonusscore.png
  src/res/tile/tile_lineeraser1.png
  src/res/tile/tile_lineeraser2.png
  src/tetrisgame/TetrisGame.java
  src/tetrisgame/component/IGameComponent.java
  src/tetrisgame/component/animation/BounusScoreItemAnim.java
  src/tetrisgame/component/animation/IAnim.java
  src/tetrisgame/component/animation/LineEraserItemAnim.java
  src/tetrisgame/component/animation/LineRemovingAnim.java
  src/tetrisgame/component/animation/RemovingAllItemAnim.java
  src/tetrisgame/component/animation/SlowingItemAnim.java
  src/tetrisgame/component/animation/WeightItemAnim.java
  src/tetrisgame/component/score/Score.java
  src/tetrisgame/component/tetromino/BonusScoreItemTetroino.java
  src/tetrisgame/component/tetromino/ItemTetromino.java
  src/tetrisgame/component/tetromino/LineEraserItemTetromino.java
  src/tetrisgame/component/tetromino/RemovingAllItemTetromino.java
  src/tetrisgame/component/tetromino/SlowingItemTetromino.java
  src/tetrisgame/component/tetromino/Tetromino.java
  src/tetrisgame/component/tetromino/WeightItemTetromino.java
  src/tetrisgame/component/tile/BonusScoreItemTile.java
  src/tetrisgame/component/tile/ItemTile.java
  src/tetrisgame/component/tile/LineEraserItemTile.java
  src/tetrisgame/component/tile/RemovingAllItemTile.java
  src/tetrisgame/component/tile/SlowingItemTile.java
  src/tetrisgame/component/tile/Tile.java
  src/tetrisgame/enumerations/eCollResult.java
  src/tetrisgame/enumerations/eGameOver.java
  src/tetrisgame/enumerations/eMsg.java
  src/tetrisgame/parts/GameBoard.java
  src/tetrisgame/parts/ImageLoader.java
  src/tetrisgame/parts/Tetromino.java
  src/tetrisgame/parts/Tile.java
  src/tetrisgame/util/ImageLoader.java
  src/tetrisgame/util/Position.java
  src/tetrisgame/util/Timer.java
Labels: 🌈 feature, 🏭 refactor

#51 fix: loadImage non-null 해결 & res파일을 images 파일로 이동
  images/background/background_board.png
  images/background/background_nextboard.png
  images/background/background_panel.png
  images/tile/item_tile_lineeraser.png
  images/tile/item_tile_removingall.png
  images/tile/item_tile_slowing.png
  images/tile/item_tile_weight.png
  images/tile/tile_blue.png
  images/tile/tile_frame.png
  images/tile/tile_item_bonusscore.png
  images/tile/tile_lightgreen.png
  images/tile/tile_lineeraser1.png
  images/tile/tile_lineeraser2.png
  images/tile/tile_orange.png
  images/tile/tile_purple.png
  images/tile/tile_red.png
  images/tile/tile_remove1.png
  images/tile/tile_remove2.png
  images/tile/tile_skyblue.png
  images/tile/tile_white.png
  images/tile/tile_yellow.png
  src/tetrisgame/util/ImageLoader.java
Labels: 😢 bug

#56 Diff change bug
  src/TestMain.java
  src/gamestarter/GameStarter.java
  src/tetrisgame/TetrisGame.java
  src/tetrisgame/component/tetromino/Tetromino.java
  src/tetrisgame/util/ImageLoader.java
Labels: 😢 bug

#42 [Feat]: scoreboard, setting 데이터 관리
  .gitignore
  build.gradle
  database/Setting.json
  database/tetrisgame
  src/data/score/Difficulty.java
  src/data/score/Mode.java
  src/data/score/Score.java
  src/data/score/ScoreBoardData.java
  src/data/score/ScoreBoardInfo.java
  src/data/score/ScoreInfo.java
  src/data/setting/BlindMode.java
  src/data/setting/DefaultSetting.java
  src/data/setting/SettingData.java
  src/data/setting/SettingInfoDesc.java
  src/graphics/WindowManager.java
  src/graphics/screens/GameScreen.java
  src/graphics/screens/ScoreBoardScreen.java
  src/graphics/screens/ScoreRenderer.java
  src/graphics/screens/SettingMenuScreen.java
  src/test/java/data/score/ScoreBoardDataTest.java
  src/test/java/data/setting/SettingDataTest.java
Labels: 🌈 feature, 💡 test

#58 feature: 게임 화면 사이즈, 키설정을 설정을 반영
  images/background/background_board.png
  images/background/background_nextboard.png
  src/TestMain.java
  src/data/setting/SettingData.java
  src/gamestarter/GameStarter.java
  src/graphics/WindowManager.java
  src/graphics/screens/GameScreen.java
  src/graphics/screens/ItemModeGameScreen.java
  src/graphics/screens/ScoreBoardScreen.java
  src/graphics/screens/SettingMenuScreen.java
  src/tetrisgame/TetrisGame.java
  src/tetrisgame/component/tetromino/BonusScoreItemTetroino.java
  src/tetrisgame/component/tetromino/LineEraserItemTetromino.java
  src/tetrisgame/component/tetromino/RemovingAllItemTetromino.java
  src/tetrisgame/component/tetromino/SlowingItemTetromino.java
  src/tetrisgame/component/tetromino/Tetromino.java
  src/tetrisgame/component/tetromino/WeightItemTetromino.java
Labels: 🌈 feature

#60 chore: add assets
  images/colorblind/btn_blue_yellow.png
  images/colorblind/btn_blue_yellow_focus.png
  images/colorblind/btn_normal.png
  images/colorblind/btn_normal_focus.png
  images/colorblind/btn_red_green.png
  images/colorblind/btn_red_green_focus.png
  images/common/btn_back.png
  images/common/btn_back_focus.png
  images/difficulty/btn_easy.png
  images/difficulty/btn_hard.png
  images/difficulty/btn_normal.png
  images/icon/tetris_icon_en.ico
  images/icon/tetris_icon_kr.ico
  images/keysetting/btn_down.png
  images/keysetting/btn_down_focus.png
  images/keysetting/btn_hard_drop.png
  images/keysetting/btn_hard_drop_focus.png
  images/keysetting/btn_left.png
  images/keysetting/btn_left_focus.png
  images/keysetting/btn_right.png
  images/keysetting/btn_right_focus.png
  images/keysetting/btn_rotate.png
  images/keysetting/btn_rotate_focus.png
  images/keysetting/current_key.png
  images/main/btn_exit.png
  images/main/btn_item_mode.png
  images/main/btn_score_board.png
  images/main/btn_setting.png
  images/main/btn_start.png
  images/main/main_background.png
  images/scoreboard/btn_default.png
  images/scoreboard/btn_default_focus.png
  images/scoreboard/btn_item.png
  images/scoreboard/btn_item_focus.png
  images/scoreboard/btn_next_page.png
  images/scoreboard/btn_next_page_focus.png
  images/scoreboard/score_info.png
  images/settings/btn_color_blind_mode.png
  images/settings/btn_color_blind_mode_focus.png
  images/settings/btn_game_key.png
  images/settings/btn_game_key_focus.png
  images/settings/btn_reset_scoreboard.png
  images/settings/btn_reset_scoreboard_focus.png
  images/settings/btn_reset_setting.png
  images/settings/btn_reset_setting_focus.png
  images/settings/btn_screen_size.png
  images/settings/btn_screen_size_focus.png
  images/size/1080.png
  images/size/1080_focus.png
  images/size/1280.png
  images/size/1280_focus.png
  images/size/720.png
  images/size/720_focus.png
Labels: chore

#73 hotfix: scoreboard data json으로 다루도록 변경
  build.gradle
  database/DefaultModeScore.json
  database/ItemModeScore.json
  database/tetrisgame
  src/data/score/ScoreBoardData.java
  src/data/setting/SettingData.java
  src/test/java/data/score/ScoreBoardDataTest.java
  src/test/java/data/setting/SettingDataTest.java
  src/tetrisgame/util/ImageLoader.java
Labels: 😢 bug, 🌈 feature

#67 feature: connect game and db
  database/Setting.json
  src/TestMain.java
  src/graphics/screens/GameScreen.java
  src/graphics/screens/ItemModeGameScreen.java
  src/tetrisgame/TetrisGame.java
  src/tetrisgame/util/ImageLoader.java
Labels: 🌈 feature

#76 hotfix: btn_back.png 추가 및 btn_Item_mode_focus.png lower-case 로 수정
  images/common/btn_back.png
  images/common/btn_back_focus.png
  images/main/btn_item_mode_focus.png
Labels: 😢 bug, chore
